version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: arp_postgres
    restart: always
    environment:
      POSTGRES_USER: arp_user
      POSTGRES_PASSWORD: arp_pass
      POSTGRES_DB: arp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: arp_redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: arp_backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://arp_user:arp_pass@postgres:5432/arp_db
      REDIS_URL: redis://redis:6379
    volumes:
      - evidence_data:/app/evidence

  ai-service:
    build: ./ai-service
    container_name: arp_ai
    ports:
      - "8001:8001"
    depends_on:
      - backend
    volumes:
      - evidence_data:/app/evidence


volumes:
  postgres_data:
  evidence_data:
